# Generated by Django 5.0.2 on 2024-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_steps_is_html',
            field=models.BooleanField(default=False),
        ),
    ]
